config/routes.rb
Service::Application.routes.draw do
  resources :courses

  resources :students

  resources :records
  
  resources :assignments do
     resources :appointments
  end
  
  resources :attendence
  

   root :to => 'students#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :account, :name
  has_many :assignments
  has_many :records, :through => :assignments
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.xml {render xml: @student} 
      # show.html.erb
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.js
      format.json { head :success}
      format.html { redirect_to @student, notice: 'Student was successfully deleted.' }
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :account %><br />
    <%= f.text_field :account %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/destroy.js.erb
alert('test');
$('#<%= dom_id(@student) %>').fadeOut();

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <% @students.each do |student| %>
  <%= content_tag_for(:tr, student) do %>
      <td><%= link_to "#{student.name}(#{student.account})", student %></td>
    <td><%= button_to 'Edit', edit_student_path(student) %></td>
    <td><%= button_to 'Remove', student, method: :delete , remote: true%></td>
  </tr>
<%end%>
<% end %>
</table>

<br />

<%= button_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Account:</b>
  <%= @student.account %>
</p>

<% @student.assignments.each do |a| %> 
<p>
    <h3><%= "#{a.course.year}-#{a.course.semester}" %></h3>
    <h4>Attendence</h4>
    <ul>
        <% a.records.each do |r| %>
            <li><%="#{r.calendar.date}: #{r.status}" %></li>
        <%end %>
    </ul>
    <h4>Appointment</h4>
    <%= link_to 'Add Appointment', new_assignment_appointment_path(a) %>
    <ul>
        <% a.appointments.each do |p| %>
            <li><%="#{p.time}:   #{p.status}"%></li>
        <%end%>
    </ul>
</p>
<% end %>
<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>