config/routes.rb
Service::Application.routes.draw do
  resources :courses

  resources :students

  resources :records
  
  resources :assignments do
     resources :appointments
  end
  
  resources :attendence
  

   root :to => 'students#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :assignment_id, :assignment, :status, :time
  belongs_to :assignment
  validates :time , :presence => true
  validates :assignment , :presence => true

  def update_status(status)
    self.status = status
    self.save
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # GET /appointments
  # GET /appointments.json

  before_filter :get_assignment

  def get_assignment 
    @assignment = Assignment.find(params[:assignment_id])
  end

  def index
    @appointments = @assignment.appointments

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @appointments }
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/new
  # GET /appointments/new.json
  def new
    @appointment = Appointment.new
    @appointment.assignment = @assignment
    @appointment.status = 'request'
    @appointment.save

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/1/edit
  def edit
    @appointment = Appointment.find(params[:id])
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = @assignment.appointments.new(params[:appointment])

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to [@assignment, @appointment], notice: 'Appointment was successfully created.' }
        format.json { render json: [@assignment, @appointment], status: :created, location: [@assignment, @appointment] }
      else
        format.html { render action: "new" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appointments/1
  # PUT /appointments/1.json
  def update
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      if @appointment.update_attributes(params[:appointment])
        format.html { redirect_to [@assignment, @appointment], notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to assignment_appointments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for([@assignment, @appointment]) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
      Hi, <%=@assignment.student.name %> <br/>
      You're making appointment for class <b>
          <%= "#{@assignment.course.year}-#{@assignment.course.semester}"%></b>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, ['Request','Cancel', 'Finish'] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@assignment, @appointment] %> |
<%= link_to 'Back', assignment_appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<h2>Course: <%="#{@assignment.course.year}-#{@assignment.course.semester}"%> </h2>
<table>
  <tr>
    <th>Student</th>
    <th>Time</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @appointments.each do |appointment| %>
  <tr>
    <td><%= appointment.assignment.student.name %></td>
    <td><%= appointment.time %></td>
    <td><%= appointment.status %></td>
    <td><%= link_to 'Show', appointment %></td>
    <td><%= link_to 'Edit', edit_assignment_appointment_path(@assignment, appointment) %></td>
    <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Appointment', new_assignment_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignment_appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Assignment:</b>
  <%= @appointment.assignment_id %>
</p>

<p>
  <b>Time:</b>
  <%= @appointment.time %>
</p>

<p>
  <b>Status:</b>
  <%= @appointment.status %>
</p>


<%= link_to 'Edit', edit_assignment_appointment_path(@assignment, @appointment) %> |
<%= link_to 'Back', assignment_appointments_path %>